/**
 * Application Preview PDF generator — produces a printable, government-style
 * application printout for the prototype. Not an official document.
 */

import { jsPDF } from "jspdf";
import { departmentById, type Service } from "./demo-data";
import { getServiceForm, type FieldDef, type SectionDef } from "./form-schemas";
import type { DocStatus } from "@/state/app-state";

export type PreviewPayload = {
  service: Service;
  reference: string;
  date: string;
  values: Record<string, string>;
  modified: string[];
  documents: Record<string, DocStatus>;
  declared: boolean;
};

const INK = [17, 22, 30] as const;
const MUTED = [95, 105, 120] as const;
const RULE = [190, 196, 205] as const;
const ACCENT = [176, 106, 20] as const;
const GREEN = [21, 110, 74] as const;

export function buildApplicationPdf(payload: PreviewPayload): jsPDF {
  const { service, reference, date, values, modified, documents, declared } = payload;
  const dept = departmentById(service.department);
  const form = getServiceForm(service.id);

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 46;
  let y = 0;

  const ensure = (need: number) => {
    if (y + need > H - 70) {
      footer();
      doc.addPage();
      y = M;
    }
  };

  const footer = () => {
    doc.setDrawColor(...RULE);
    doc.line(M, H - 56, W - M, H - 56);
    doc
      .setFont("helvetica", "italic")
      .setFontSize(8)
      .setTextColor(...MUTED);
    doc.text(
      "Generated by LOK SEVAK — Application Preview for Prototype Demonstration. This is not an official government-issued document.",
      W / 2,
      H - 42,
      { align: "center", maxWidth: W - 2 * M },
    );
    doc.text(`Reference ${reference}`, W / 2, H - 30, { align: "center" });
  };

  // ---- Header -------------------------------------------------------------
  doc.setFillColor(...INK);
  doc.rect(0, 0, W, 84, "F");
  doc.setFont("helvetica", "bold").setFontSize(20).setTextColor(255, 255, 255);
  doc.text("LOK SEVAK", M, 38);
  doc.setFont("helvetica", "normal").setFontSize(9).setTextColor(226, 208, 178);
  doc.text("Unified Citizen Services Platform · Government Service Application Preview", M, 54);
  doc.setFontSize(8).setTextColor(200, 200, 200);
  doc.text("Prototype Demonstration", W - M, 38, { align: "right" });
  doc.text(date, W - M, 54, { align: "right" });

  y = 108;

  // ---- Service identity ---------------------------------------------------
  doc.setDrawColor(...RULE).setLineWidth(0.8);
  doc.rect(M, y - 22, W - 2 * M, 74);
  doc
    .setFont("helvetica", "bold")
    .setFontSize(14)
    .setTextColor(...INK);
  doc.text(service.name.toUpperCase(), M + 12, y - 4);
  doc
    .setFont("helvetica", "normal")
    .setFontSize(9)
    .setTextColor(...MUTED);
  doc.text(`${dept.name} · ${dept.systemName}`, M + 12, y + 10);
  doc.setTextColor(...INK);
  doc.text(`Application Reference : ${reference}`, M + 12, y + 26);
  doc.text(`Application Date : ${date}`, M + 12, y + 40);
  doc.setFont("helvetica", "bold").setTextColor(...ACCENT);
  doc.text("STATUS : PREVIEW", W - M - 12, y + 26, { align: "right" });
  y += 74;

  const heading = (text: string) => {
    ensure(40);
    y += 18;
    doc.setFillColor(240, 241, 244);
    doc.rect(M, y - 12, W - 2 * M, 20, "F");
    doc
      .setFont("helvetica", "bold")
      .setFontSize(10)
      .setTextColor(...INK);
    doc.text(text.toUpperCase(), M + 8, y + 2);
    y += 20;
  };

  const row = (label: string, value: string, flag?: string) => {
    const lines = doc.splitTextToSize(value || "—", W - 2 * M - 210) as string[];
    const h = Math.max(16, lines.length * 12 + 4);
    ensure(h);
    doc
      .setFont("helvetica", "normal")
      .setFontSize(9)
      .setTextColor(...MUTED);
    doc.text(label, M + 8, y + 4);
    doc.setFont("helvetica", "bold").setTextColor(...INK);
    doc.text(lines, M + 205, y + 4);
    if (flag) {
      doc
        .setFont("helvetica", "normal")
        .setFontSize(7)
        .setTextColor(...ACCENT);
      doc.text(flag, W - M - 8, y + 4, { align: "right" });
    }
    y += h;
    doc.setDrawColor(232, 234, 238).setLineWidth(0.4);
    doc.line(M + 8, y - 6, W - M - 8, y - 6);
  };

  const renderSections = (sections: SectionDef[]) => {
    for (const section of sections) {
      heading(section.title);
      for (const f of section.fields as FieldDef[]) {
        row(
          f.label,
          values[f.key] ?? "",
          modified.includes(f.key) ? "modified for this application" : undefined,
        );
      }
    }
  };

  if (form) {
    renderSections(form.applicant);
    heading(`${service.name} — Service Details`);
    for (const section of form.serviceDetails) {
      for (const f of section.fields) {
        row(
          f.label,
          values[f.key] ?? "",
          modified.includes(f.key) ? "modified for this application" : undefined,
        );
      }
    }

    heading("Document Checklist");
    for (const d of form.documents) {
      const status = documents[d] ?? "Required";
      const mark = status === "Available" || status === "Uploaded" ? "[X]" : "[ ]";
      ensure(16);
      doc
        .setFont("helvetica", "normal")
        .setFontSize(9)
        .setTextColor(...INK);
      doc.text(`${mark}  ${d}`, M + 8, y + 4);
      doc.setTextColor(...MUTED);
      doc.text(status, W - M - 8, y + 4, { align: "right" });
      y += 16;
    }

    heading("Declaration");
    ensure(60);
    doc
      .setFont("helvetica", "normal")
      .setFontSize(9)
      .setTextColor(...INK);
    const decl = doc.splitTextToSize(form.declaration, W - 2 * M - 16) as string[];
    doc.text(decl, M + 8, y + 4);
    y += decl.length * 12 + 10;
    const declColor = declared ? GREEN : MUTED;
    doc.setFont("helvetica", "bold").setTextColor(declColor[0], declColor[1], declColor[2]);
    doc.text(
      declared
        ? "Declaration Status : ACCEPTED — Applicant confirmed the information is correct for this prototype demonstration."
        : "Declaration Status : NOT ACCEPTED",
      M + 8,
      y + 4,
      { maxWidth: W - 2 * M - 16 },
    );
    y += 34;

    ensure(60);
    doc.setDrawColor(...RULE).setLineWidth(0.6);
    doc.line(W - M - 170, y + 34, W - M - 8, y + 34);
    doc
      .setFont("helvetica", "normal")
      .setFontSize(8)
      .setTextColor(...MUTED);
    doc.text("Signature of Applicant", W - M - 8, y + 46, { align: "right" });
    doc.text(`Place : ${values["city"] ?? "Nagpur"}`, M + 8, y + 46);
  }

  footer();
  return doc;
}

export function downloadApplicationPdf(payload: PreviewPayload) {
  buildApplicationPdf(payload).save(`LOK-SEVAK-${payload.reference}.pdf`);
}

export function applicationPdfDataUri(payload: PreviewPayload): string {
  return buildApplicationPdf(payload).output("datauristring");
}
