/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as InteroperabilityRouteImport } from './routes/interoperability'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ApplicationsApplicationIdRouteImport } from './routes/applications/$applicationId'
import { Route as ApplyServiceIdRouteImport } from './routes/apply.$serviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const InteroperabilityRoute = InteroperabilityRouteImport.update({
  id: '/interoperability',
  path: '/interoperability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsApplicationIdRoute =
  ApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => ApplicationsRoute,
  } as any)
const ApplyServiceIdRoute = ApplyServiceIdRouteImport.update({
  id: '/apply/$serviceId',
  path: '/apply/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/interoperability': typeof InteroperabilityRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/apply/$serviceId': typeof ApplyServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/interoperability': typeof InteroperabilityRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/apply/$serviceId': typeof ApplyServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/interoperability': typeof InteroperabilityRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/apply/$serviceId': typeof ApplyServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/assistant'
    | '/interoperability'
    | '/profile'
    | '/services'
    | '/applications/$applicationId'
    | '/apply/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/assistant'
    | '/interoperability'
    | '/profile'
    | '/services'
    | '/applications/$applicationId'
    | '/apply/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/assistant'
    | '/interoperability'
    | '/profile'
    | '/services'
    | '/applications/$applicationId'
    | '/apply/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  InteroperabilityRoute: typeof InteroperabilityRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRoute
  ApplyServiceIdRoute: typeof ApplyServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interoperability': {
      id: '/interoperability'
      path: '/interoperability'
      fullPath: '/interoperability'
      preLoaderRoute: typeof InteroperabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId': {
      id: '/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof ApplicationsApplicationIdRouteImport
      parentRoute: typeof ApplicationsRoute
    }
    '/apply/$serviceId': {
      id: '/apply/$serviceId'
      path: '/apply/$serviceId'
      fullPath: '/apply/$serviceId'
      preLoaderRoute: typeof ApplyServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApplicationsRouteChildren {
  ApplicationsApplicationIdRoute: typeof ApplicationsApplicationIdRoute
}

const ApplicationsRouteChildren: ApplicationsRouteChildren = {
  ApplicationsApplicationIdRoute: ApplicationsApplicationIdRoute,
}

const ApplicationsRouteWithChildren = ApplicationsRoute._addFileChildren(
  ApplicationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRouteWithChildren,
  AssistantRoute: AssistantRoute,
  InteroperabilityRoute: InteroperabilityRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRoute,
  ApplyServiceIdRoute: ApplyServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
